In [4]:
import json
import pandas as pd

In [8]:
file1 = '/home/pavan/DopeCode/mmtcfinal/home/static/FINALFLIGHTTEST.json'
file = '/home/pavan/DopeCode/mmtcfinal/home/static/FINALTRAINTEST.json'

In [9]:
with open(file) as train_file:
    dict_train = json.load(train_file)
# converting json dataset from dictionary to dataframe
train = pd.DataFrame.from_dict(dict_train, orient='columns')
train.reset_index(level=0, inplace=True)
with open(file1) as flight_file:
    dict_flight = json.load(flight_file)
flight = pd.DataFrame.from_dict(dict_flight, orient='columns')
flight.reset_index(level=0, inplace = True)

In [10]:
train

,index,1A,2A,3A,Arrival time,DAY,Dest Station Code,Dest station_name,Distance,SEQ,SL,Source Station,Source Station Name,Train Name,departure_time,train_number
0,0,580,650,970,12:30:00,136,MGS,MUGHAL SARAI,207,2,170,PNBE,PATNA,PNBE-BTI FTR,12:40:00,504
1,1,680,1060,1380,10:00:00,136,BTI,BATHINDA JN,1313,3,330,PNBE,PATNA,PNBE-BTI FTR,10:00:00,504
2,2,610,700,1050,18:10:00,1234567,MGS,MUGHAL SARAI,207,2,100,PNBE,PATNA,PNBE-PTA FTR,18:15:00,506
3,3,820,1150,1330,15:45:00,1234567,PTA,PATIALA,1161,3,300,PNBE,PATNA,PNBE-PTA FTR,15:45:00,506
4,4,370,860,990,16:20:00,67,MGS,MUGHAL SARAI,207,2,160,PNBE,PATNA,PNBE-ASR FTR,16:30:00,604
5,5,650,1160,1400,16:00:00,1234567,ASR,AMRITSAR JN.,1429,3,520,PNBE,PATNA,PNBE-ASR FTR,16:00:00,604
6,6,460,660,1030,19:55:00,67,LNL,LONAVLA,63,2,130,PUNE,PUNE,PUNE-MAJN WE,19:57:00,1301
7,7,340,880,1090,21:20:00,67,PNVL,PANVEL,120,3,300,PUNE,PUNE,PUNE-MAJN WE,21:50:00,1301
8,8,360,790,960,23:30:00,67,ROHA,ROHA,197,4,190,PUNE,PUNE,PUNE-MAJN WE,23:35:00,1301
9,9,520,680,970,0:48:00,67,KHED,KHED,300,5,230,PUNE,PUNE,PUNE-MAJN WE,0:50:00,1301
10,10,320,710,930,1:10:00,67,CHI,CHIPLUN,330,6,130,PUNE,PUNE,PUNE-MAJN WE,1:12:00,1301
11,11,320,880,910,2:25:00,67,RN,RATNAGIRI,405,7,280,PUNE,PUNE,PUNE-MAJN WE,2:30:00,1301
12,12,460,790,980,3:44:00,67,KKW,KANKAVALI,529,8,170,PUNE,PUNE,PUNE-MAJN WE,3:46:00,1301
13,13,550,760,900,4:08:00,67,KUDL,KUDAL,557,9,280,PUNE,PUNE,PUNE-MAJN WE,4:10:00,1301
14,14,650,800,940,5:04:00,67,THVM,THIVIM,611,10,130,PUNE,PUNE,PUNE-MAJN WE,5:06:00,1301
15,15,500,790,920,6:20:00,67,MAO,MADGOAN JN.,657,11,240,PUNE,PUNE,PUNE-MAJN WE,6:30:00,1301
16,16,450,820,970,7:22:00,67,KAWR,KAWR,715,12,160,PUNE,PUNE,PUNE-MAJN WE,7:24:00,1301
17,17,650,800,980,8:08:00,7,KT,KUMTA,770,13,290,PUNE,PUNE,PUNE-MAJN WE,8:10:00,1301
18,18,320,890,1070,10:00:00,1234567,KUDA,KUNDAPURA,879,14,230,PUNE,PUNE,PUNE-MAJN WE,10:02:00,1301
19,19,320,700,1040,10:36:00,1234567,UD,UDUPI,911,15,170,PUNE,PUNE,PUNE-MAJN WE,10:38:00,1301
20,20,380,820,940,11:10:00,1234,MULK,MULKI,947,16,180,PUNE,PUNE,PUNE-MAJN WE,11:12:00,1301
21,21,380,660,930,12:30:00,1234,MAJN,MANGALORE JN,976,17,240,PUNE,PUNE,PUNE-MAJN WE,12:30:00,1301
22,22,330,830,990,12:05:00,1,DD,DAUND JN.,77,2,290,PUNE,PUNE,PUNE-JBP SPL,12:20:00,1655
23,23,560,820,1040,13:57:00,6,ANG,AHMADNAGAR,161,3,100,PUNE,PUNE,PUNE-JBP SPL,14:00:00,1655
24,24,630,800,940,15:58:00,7,KPG,KOPARGAON,272,4,220,PUNE,PUNE,PUNE-JBP SPL,16:00:00,1655
25,25,540,880,980,17:20:00,1234567,MMR,MANMAD JN.,314,5,210,PUNE,PUNE,PUNE-JBP SPL,17:25:00,1655
26,26,630,901,1080,20:10:00,1234567,BSL,BHUSAVAL JN.,498,6,220,PUNE,PUNE,PUNE-JBP SPL,20:20:00,1655
27,27,440,900,980,23:40:00,1234567,KNW,KHANDWA JN.,621,7,290,PUNE,PUNE,PUNE-JBP SPL,23:45:00,1655
28,28,510,700,980,0:55:00,5,HD,HARDA,729,8,270,PUNE,PUNE,PUNE-JBP SPL,0:57:00,1655
29,29,390,820,1060,2:15:00,5,ET,ITARSI,805,9,300,PUNE,PUNE,PUNE-JBP SPL,2:30:00,1655
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18657,18657,380,800,1000,9:15:00,134567,KSWD,KASARWADI,11,5,190,PUNE,PUNE,PUNE-TGN EMU,9:16:00,99904
18658,18658,420,840,920,9:18:00,2,PMP,PIMPRI,14,6,260,PUNE,PUNE,PUNE-TGN EMU,9:19:00,99904
18659,18659,460,700,910,9:22:00,1234567,CCH,CHINCHVAD,16,7,170,PUNE,PUNE,PUNE-TGN EMU,9:23:00,99904
18660,18660,600,800,960,9:26:00,1234567,AKRD,AKURDI,19,8,290,PUNE,PUNE,PUNE-TGN EMU,9:27:00,99904
18661,18661,440,850,950,9:31:00,1234567,DEHR,DEHU ROAD,24,9,240,PUNE,PUNE,PUNE-TGN EMU,9:32:00,99904
18662,18662,530,690,950,9:35:00,1234567,BGWI,BEGDAEWAI,28,10,250,PUNE,PUNE,PUNE-TGN EMU,9:36:00,99904
18663,18663,320,810,1080,9:38:00,1234567,GRWD,GHORAWADI,31,11,240,PUNE,PUNE,PUNE-TGN EMU,9:39:00,99904
18664,18664,400,880,1090,9:47:00,1234567,TGN,TALEGAON,34,12,240,PUNE,PUNE,PUNE-TGN EMU,9:47:00,99904
18665,18665,610,750,1010,15:44:00,124567,SVJR,SHIVAJINAGAR,2,2,160,PUNE,PUNE,EMU,15:45:00,99906
18666,18666,400,900,960,15:49:00,124567,KK,KHADKI,6,3,180,PUNE,PUNE,EMU,15:50:00,99906
18667,18667,340,840,1080,15:54:00,3,DAPD,DAPODI,8,4,260,PUNE,PUNE,EMU,15:55:00,99906
18668,18668,430,760,1030,15:58:00,3,KSWD,KASARWADI,11,5,220,PUNE,PUNE,EMU,15:59:00,99906
18669,18669,560,730,1090,16:01:00,3,PMP,PIMPRI,14,6,290,PUNE,PUNE,EMU,16:02:00,99906
18670,18670,620,790,1080,16:05:00,1234567,CCH,CHINCHVAD,16,7,120,PUNE,PUNE,EMU,16:06:00,99906
18671,18671,510,730,1020,16:09:00,1234567,AKRD,AKURDI,19,8,180,PUNE,PUNE,EMU,16:10:00,99906
18672,18672,370,730,1050,16:14:00,1234567,DEHR,DEHU ROAD,24,9,240,PUNE,PUNE,EMU,16:15:00,99906
18673,18673,460,740,1000,16:18:00,1234567,BGWI,BEGDAEWAI,28,10,280,PUNE,PUNE,EMU,16:19:00,99906
18674,18674,560,880,1070,16:21:00,1234567,GRWD,GHORAWADI,31,11,210,PUNE,PUNE,EMU,16:22:00,99906
18675,18675,630,770,900,16:30:00,1234567,TGN,TALEGAON,34,12,140,PUNE,PUNE,EMU,16:30:00,99906
18676,18676,400,860,1050,23:04:00,1234567,SVJR,SHIVAJINAGAR,2,2,100,PUNE,PUNE,EMU,23:05:00,99908
18677,18677,330,670,1030,23:09:00,1234567,KK,KHADKI,6,3,230,PUNE,PUNE,EMU,23:10:00,99908
18678,18678,330,860,910,23:15:00,1234567,DAPD,DAPODI,8,4,190,PUNE,PUNE,EMU,23:16:00,99908
18679,18679,580,810,960,23:19:00,1234567,KSWD,KASARWADI,11,5,280,PUNE,PUNE,EMU,23:20:00,99908
18680,18680,540,720,980,23:22:00,1234567,PMP,PIMPRI,14,6,220,PUNE,PUNE,EMU,23:23:00,99908
18681,18681,340,840,980,23:26:00,1234567,CCH,CHINCHVAD,16,7,200,PUNE,PUNE,EMU,23:27:00,99908
18682,18682,520,770,1000,23:30:00,1234567,AKRD,AKURDI,19,8,270,PUNE,PUNE,EMU,23:31:00,99908
18683,18683,530,740,910,23:35:00,1234567,DEHR,DEHU ROAD,24,9,250,PUNE,PUNE,EMU,23:36:00,99908
18684,18684,400,710,990,23:39:00,1234567,BGWI,BEGDAEWAI,28,10,140,PUNE,PUNE,EMU,23:40:00,99908
18685,18685,530,720,1080,23:41:00,1234567,GRWD,GHORAWADI,31,11,120,PUNE,PUNE,EMU,23:42:00,99908
18686,18686,550,880,920,23:50:00,1234567,TGN,TALEGAON,34,12,210,PUNE,PUNE,EMU,0:00:00,99908

source = str(input("Enter source\n")).upper()
destination = str(input("Enter destination\n")).upper()

s = []
for i in range(0,train.shape[0]):
    b = []
    if train.iloc[i,12] == source:
        if train.iloc[i,7] == destination:
            print(train.iloc[i,1:])
            print('\n\n\n')
            b.append(train.iloc[i,:])
            s.append(b)
            
g = []
for i in range(0,flight.shape[0]):
    b = []
    if flight.iloc[i,7] == source:
        if flight.iloc[i,10] == destination:
            print(flight.iloc[i,1:])
            print('\n\n\n')
            b.append(flight.iloc[i,:])
            g.append(b)

In [11]:
source = str(input("Enter source\n")).upper()
destination = str(input("Enter destination\n")).upper()

s = []
for i in range(0,train.shape[0]):
    b = []
    if train.iloc[i,12] == source:
        if train.iloc[i,7] == destination:
            print(train.iloc[i,1:])
            print('\n\n\n')
            b.append(train.iloc[i,:])
            s.append(b)
            
g = []
for i in range(0,flight.shape[0]):
    b = []
    if flight.iloc[i,7] == source:
        if flight.iloc[i,10] == destination:
            print(flight.iloc[i,1:])
            print('\n\n\n')
            b.append(flight.iloc[i,:])
            g.append(b)

Enter source
tirupati
Enter destination
nellore
1A                          320
2A                          810
3A                          940
Arrival time           20:00:00
DAY                     1234567
Dest Station Code           NLR
Dest station_name       NELLORE
Distance                    131
SEQ                           3
SL                          280
Source Station             TPTY
Source Station Name    TIRUPATI
Train Name             VSKP HSP
departure_time         20:02:00
train_number               7044
Name: 220, dtype: object




1A                          620
2A                          660
3A                         1040
Arrival time           19:22:00
DAY                           2
Dest Station Code           NLR
Dest station_name       NELLORE
Distance                    131
SEQ                           5
SL                          200
Source Station             TPTY
Source Station Name    TIRUPATI
Train Name             TPTY-KCG
departure_time         19:23:00
train_number               7146
Name: 232, dtype: object




1A                              430
2A                              900
3A                             1090
Arrival time                9:48:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               4
SL                              270
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-NSL HSP
departure_time              9:50:00
train_number                   7417
Name: 274, dtype: object




1A                          350
2A                          650
3A                          990
Arrival time           16:40:00
DAY                     1234567
Dest Station Code           NLR
Dest station_name       NELLORE
Distance                    131
SEQ                           4
SL                          240
Source Station             TPTY
Source Station Name    TIRUPATI
Train Name              TPTY-SC
departure_time         16:42:00
train_number               7430
Name: 306, dtype: object




1A                          570
2A                          880
3A                         1040
Arrival time           19:21:00
DAY                      123456
Dest Station Code           NLR
Dest station_name       NELLORE
Distance                    131
SEQ                           5
SL                          220
Source Station             TPTY
Source Station Name    TIRUPATI
Train Name             TPTY-CCT
departure_time         19:23:00
train_number               7432
Name: 317, dtype: object




1A                           540
2A                           880
3A                           960
Arrival time             0:40:00
DAY                      1234567
Dest Station Code            NLR
Dest station_name        NELLORE
Distance                     131
SEQ                            3
SL                           180
Source Station              TPTY
Source Station Name     TIRUPATI
Train Name             TPTY-VSKP
departure_time           0:42:00
train_number                7487
Name: 328, dtype: object




1A                          440
2A                          770
3A                         1050
Arrival time           18:18:00
DAY                     1234567
Dest Station Code           NLR
Dest station_name       NELLORE
Distance                    131
SEQ                           5
SL                          120
Source Station             TPTY
Source Station Name    TIRUPATI
Train Name             TPTY-NED
departure_time         18:20:00
train_number               7608
Name: 340, dtype: object




1A                             560
2A                             820
3A                             960
Arrival time              21:28:00
DAY                        1234567
Dest Station Code              NLR
Dest station_name          NELLORE
Distance                       131
SEQ                              5
SL                             300
Source Station                TPTY
Source Station Name       TIRUPATI
Train Name             TPTY-COASPL
departure_time            21:30:00
train_number                  7942
Name: 358, dtype: object




1A                              320
2A                              880
3A                              970
Arrival time               18:00:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               5
SL                              140
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-VSKP SP
departure_time             18:02:00
train_number                   8574
Name: 435, dtype: object




1A                              540
2A                              690
3A                             1050
Arrival time               20:42:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               6
SL                              160
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-SC NARA
departure_time             20:44:00
train_number                  12733
Name: 3254, dtype: object




1A                              520
2A                              670
3A                              970
Arrival time               19:22:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               6
SL                              110
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-SC PADM
departure_time             19:23:00
train_number                  12763
Name: 3333, dtype: object




1A                             580
2A                             670
3A                             970
Arrival time              22:04:00
DAY                        1234567
Dest Station Code              NLR
Dest station_name          NELLORE
Distance                       131
SEQ                              7
SL                             110
Source Station                TPTY
Source Station Name       TIRUPATI
Train Name             TPTY-MTM NS
departure_time            22:06:00
train_number                 17401
Name: 6736, dtype: object




1A                              590
2A                              900
3A                             1000
Arrival time                8:09:00
DAY                           12567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               8
SL                              130
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-ADB KRI
departure_time              8:11:00
train_number                  17405
Name: 6757, dtype: object




1A                              530
2A                              760
3A                              910
Arrival time               13:30:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               7
SL                              290
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-PURI EX
departure_time             13:32:00
train_number                  17480
Name: 6989, dtype: object




1A                              560
2A                              740
3A                             1000
Arrival time               13:31:00
DAY                              17
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               7
SL                              290
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-BSP EXP
departure_time             13:32:00
train_number                  17482
Name: 7061, dtype: object




1A                              570
2A                              710
3A                             1070
Arrival time               23:08:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               7
SL                              160
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-VSKP TI
departure_time             23:10:00
train_number                  17487
Name: 7126, dtype: object




1A                              350
2A                              740
3A                             1000
Arrival time                0:18:00
DAY                               2
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               5
SL                              300
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-VSKP TR
departure_time              0:20:00
train_number                  22708
Name: 9215, dtype: object




1A                              480
2A                              890
3A                             1100
Arrival time               15:17:00
DAY                          134567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               3
SL                              190
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-BBS S/F
departure_time             15:18:00
train_number                  22872
Name: 9480, dtype: object




1A                              440
2A                              770
3A                              980
Arrival time               15:17:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                               4
SL                              160
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-BBS S/F
departure_time             15:18:00
train_number                  22880
Name: 9514, dtype: object

1A                              410
2A                              670
3A                              960
Arrival time                4:44:00
DAY                               2
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                              15
SL                              280
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-COA PAS
departure_time              4:46:00
train_number                  57257
Name: 15161, dtype: object




1A                          630
2A                          850
3A                          950
Arrival time           18:00:00
DAY                     1234567
Dest Station Code           NLR
Dest station_name       NELLORE
Distance                    131
SEQ                          16
SL                          140
Source Station             TPTY
Source Station Name    TIRUPATI
Train Name                 PASS
departure_time         18:02:00
train_number              57329
Name: 15312, dtype: object




1A                              390
2A                              720
3A                             1040
Arrival time               14:50:00
DAY                         1234567
Dest Station Code               NLR
Dest station_name           NELLORE
Distance                        131
SEQ                              16
SL                              250
Source Station                 TPTY
Source Station Name        TIRUPATI
Train Name             TPTY-NLR PAS
departure_time             14:50:00
train_number                  66033
Name: 17555, dtype: object

In [26]:
for i in s:
    print(type(i))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

In [27]:
i

[index                         17555
 1A                              390
 2A                              720
 3A                             1040
 Arrival time               14:50:00
 DAY                         1234567
 Dest Station Code               NLR
 Dest station_name           NELLORE
 Distance                        131
 SEQ                              16
 SL                              250
 Source Station                 TPTY
 Source Station Name        TIRUPATI
 Train Name             TPTY-NLR PAS
 departure_time             14:50:00
 train_number                  66033
 Name: 17555, dtype: object]

In [31]:
i

[index                         17555
 1A                              390
 2A                              720
 3A                             1040
 Arrival time               14:50:00
 DAY                         1234567
 Dest Station Code               NLR
 Dest station_name           NELLORE
 Distance                        131
 SEQ                              16
 SL                              250
 Source Station                 TPTY
 Source Station Name        TIRUPATI
 Train Name             TPTY-NLR PAS
 departure_time             14:50:00
 train_number                  66033
 Name: 17555, dtype: object]

In [41]:


import json
row = [['1L',7],[0.1,0.2],['1234L',1],['134L',2]]
k = pd.DataFrame(i)

In [47]:
k.iloc[:,0]

17555    17555
Name: index, dtype: int64